<?php
$objectManager  = \Magento\Framework\App\ObjectManager::getInstance();
$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
$categories     = $categoryHelper->getStoreCategories();
foreach ($categories as $category):
    $categoriesStore[] = $category->getId();
endforeach;

$categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$categories         = $categoryCollection->create()->addAttributeToSelect('*');
?>

<div class="m-t-30">
    <!-- .product-category-widget-1-->
    <div class="product-category-widget-1">
        <div class="categories-widget m-b-50">
            <h3 class="title text-block text-black text-sm m-b-15">
                <?php echo __('Categories');?>
            </h3>
        </div>
        <ul class="vertical-list">
            <?php foreach ($categories as $category):?>
                <?php if(in_array($category->getId(), $categoriesStore) AND $category->getProductCount() > 0 ):?>
                    <li>
                        <a href="<?php echo $category->getUrl();?>"><?php echo $category->getName(); ?></a>
                    </li>
                <?php endif;?>
            <?php endforeach;?>
        </ul>
    </div>
    <!-- end .product-category-widget-1-->
</div>