<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<tr>
    <td class="actions" colspan="6">
        <div class="woo-cart-form-coupon">
            <p class="text-block text-black text-bold"><?= /* @escapeNotVerified */ __('COUPON CODE') ?></p>
            <form id="discount-coupon-form"
                  action="<?= /* @escapeNotVerified */ $block->getUrl('checkout/cart/couponPost') ?>"
                  method="post"
                  data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                                   "removeCouponSelector": "#remove-coupon",
                                                   "applyButton": "button.action.apply",
                                                   "cancelButton": "button.action.cancel"}}'>
                <div class="coupon-content <?= strlen($block->getCouponCode()) ? ' applied' : '' ?>">
                    <div class="form-group">
                        <input type="hidden" name="remove" id="remove-coupon" value="0" />
                        <input type="text" class="au-input-1" id="coupon_code" name="coupon_code" value="<?= $block->escapeHtml($block->getCouponCode()) ?>" placeholder="<?= $block->escapeHtml(__('Enter your coupon here')) ?>" />
                    </div>
                    <?php if (!strlen($block->getCouponCode())): ?>
                    <button class="au-btn au-btn-border" type="button" value="<?= /* @escapeNotVerified */ __('Apply Discount') ?>">
                        <span><?= /* @escapeNotVerified */ __('Apply Discount') ?></span>
                    </button>
                    <?php else: ?>
                        <button  type="button" class="au-btn au-btn-border cancel primary" value="<?= /* @escapeNotVerified */ __('Cancel Coupon') ?>"><span><?= /* @escapeNotVerified */ __('Cancel Coupon') ?></span></button>
                    <?php endif; ?>
                </div>
            </form>
        </div>
    </td>
</tr>
