<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    // init current time now
    $currentTime = new DateTime();

    $image = 'new_products_content_widget_grid';
    $title = __('OUR PRODUCTS');
    $items = $block->getProductCollection()
        ->setOrder('sort_order', 'ASC')
        ->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
}
?>

<?php if ($exist):?>
    <section class="section section-product bg-white p-t-70 p-b-60">
        <div class="container1">
            <div class="heading-section text-center"><h3>New products</h3></div>
            <div class="owl-carousel owl-style-2" data-carousel-margin="0" data-carousel-loop="true"
                 data-carousel-dots="true" data-carousel-autoplay="false" data-carousel-items="1" data-carousel-lg="1"
                 data-carousel-xs="1" data-carousel-sm="1" data-carousel-md="1">
                <ul class="list-reset product-list row">
                    <?php $count = 0; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php if($count%4==0 AND $count > 0):?>
                            </ul><ul class="list-reset product-list row">
                        <?php endif;?>
                        <li class="col-md-3 col-sm-6">
                            <div class="image-box image-box-3">
                                <div class="image">
                                    <a class="bg-overlay" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"></a>
                                    <img src="<?php echo $block->getUrl('pub/media/catalog').'product'.$_item->getImage();?>" />
                                    <a class="btn-quickview" href="#qv<?php echo $_item->getId();?>"><i class="fa fa-search-plus"></i><span>Quick view</span></a>
                                </div>
                                <div class="content">
                                    <h3 class="title">
                                        <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                           href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                           class="name">
                                            <?php echo $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </h3>
                                    <?php
                                    echo $block->getProductPriceHtml($_item, $type);
                                    ?>
                                    <?php if ($templateType): ?>
                                        <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </li>

                        <!-- quick-view-1-->
                        <div class="quickview-modal single-product remodal" data-remodal-id="qv<?php echo $_item->getId();?>">
                            <button class="remodal-close" data-remodal-action="close" aria-label="Close"></button>
                            <div class="single-product-detail customScrollbar" data-scroll-cursorcolor="#b9b9b9"
                                 data-scroll-cursorwidth="3px">
                                <div class="row-cs">
                                    <div class="col-cs-6 product-image-content">
                                        <div class="image-box"><img src="<?php echo $block->getUrl('pub/media/catalog').'product'.$_item->getImage();?>" /></div>
                                    </div>
                                    <div class="col-cs-6 product-summary">
                                        <h3 class="product-title text-block m-b-10">
                                            <a class="text-black" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>">
                                                <?php /* @escapeNotVerified */ echo $_item->getName() ?>
                                            </a>
                                        </h3>

                                        <span class="product-price m-b-15"><?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?></span>
                                        <p class="product-short-description m-b-15">
                                            <?php echo $_item->getShortDescription(); ?>
                                        </p>
                                        <div class="add-to-wishlist block-contain m-b-40">
                                            <div class="block-left" data-toggle="tooltip" title="Add to wishlist">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a class="au-btn au-btn-border au-btn-radius btn-add-to-wishlist" href="#"
                                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                    <i class="fa fa-heart"></i><span><?php echo __('ADD TO WISHLIST'); ?></span>
                                                    </a>
                                                <?php endif;?>
                                            </div>
                                            <div class="block-right" data-toggle="tooltip" title="View full details">
                                                <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                                   href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>">
                                                    <i class="fa fa-arrow-right"></i><span><?php echo __('Go to detail'); ?></span>
                                                </a>
                                            </div>
                                        </div>
                                        <form action="<?= /* @escapeNotVerified */ $block->getSubmitUrl($_item) ?>" method="post"
                                              id="product_addtocart_form_<?php echo $_item->getId();?>" enctype="multipart/form-data">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $_item->getId() ?>" />
                                            <input type="hidden" name="selected_configurable_option" value="" />
                                            <input type="hidden" name="related_product" id="related-products-field-<?php echo $_item->getId();?>" value="" />
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <div class="product-select row-cs m-b-20">
                                                <?php if (!$block->hasOptions()):?>
                                                <div class="col-cs-6 p-l-5" data-toggle="tooltip" title="Quantity">
                                                    <div class="quantity">
                                                        <span class="decrease"></span>
                                                        <input class="au-input-number"
                                                               name="qty"
                                                               id="qty_<?php echo $_item->getId();?>"
                                                               value="<?= /* @escapeNotVerified */ __('1') ?>"
                                                               title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                                                               type="number" value="1" min="1" max="100"/>
                                                        <span class="increase"></span></div>
                                                </div>
                                            </div>
                                            <button class="au-btn add-to-cart btn-block m-b-30" type="submit"><?php echo __('ADD TO CART') ?></button>
                                        <?php endif; ?>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- end quick-view-1-->
                    <?php $count++; ?>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
    </section>
<?php endif;?>

