<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>
<?php
$objectManager  = \Magento\Framework\App\ObjectManager::getInstance();
$categoryHelper = $objectManager->get('\Magento\Catalog\Helper\Category');
$categories     = $categoryHelper->getStoreCategories();
foreach ($categories as $category):
    $categoriesStore[] = $category->getId();
endforeach;

$categoryCollection = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$categories         = $categoryCollection->create()->addAttributeToSelect('*');
?>

<?php
    $_postCollection = $block->getPostCollection();
?>

<aside class="blog-with-sidebar">
    <div class="aside-wrapper">
        <div class="categories-widget m-b-50">
            <h3 class="title text-block text-black text-sm m-b-15"><?php echo __('Categories'); ?></h3>
            <ul class="vertical-list">
                <?php foreach ($categories as $category):?>
                    <?php if(in_array($category->getId(), $categoriesStore) AND $category->getProductCount() > 0 ):?>
                        <li>
                            <a href="<?php echo $category->getUrl();?>"><?php echo $category->getName(); ?></a>
                            <span class="totals">(<?php echo $category->getProductCount(); ?>)</span>
                        </li>
                    <?php endif;?>
                <?php endforeach;?>
            </ul>
        </div>
        <?php if ($_postCollection->count()) { ?>
        <div class="brands-widget m-b-50"><h3 class="title text-block text-black text-sm m-b-15"><?php echo __('Archives'); ?></h3>
            <ul class="vertical-list">
                <?php foreach ($_postCollection as $_post) { ?>
                <li>
                    <a class="name" href="<?php echo $_post->getPostUrl() ?>"> <?php echo $block->escapeHtml($_post->getTitle()) ?></a>
                </li>
                <?php } ?>
            </ul>
        </div>
        <div class="ads-wigdet"><?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mina-blog-ads')->toHtml();?></div>
    </div>
        <?php } ?>
</aside>
