<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<label><?php echo __('Short By:');?></label>
<select class="woocommerce-ordering">
    <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
        <option value="<?= /* @escapeNotVerified */ $_key ?>"
            <?php if ($block->isOrderCurrent($_key)): ?>
                selected="selected"
            <?php endif; ?>
            >
            <?= $block->escapeHtml(__($_order)) ?>
        </option>
    <?php endforeach; ?>
</select>

