<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>
<section class="section p-t-10">
    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php else: ?>
            <div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?= /* @escapeNotVerified */ $class ?>">
    <?php endif; ?>
    <div class="container">
        <div class="heading-section text-center"><h3><?= /* @escapeNotVerified */ $title ?></h3></div>
        <?php if ($type == 'related' && $canItemsAddToCart): ?>
        <ul class="list-reset product-list row">
            <?php foreach ($items as $_item): ?>
            <li class="col-md-3 col-sm-6">
                <div class="image-box image-box-3">
                    <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
                    <div class="image">
                        <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                            <img src="<?php echo $block->getUrl('pub/media/catalog').'product'.$_item->getImage();?>" />
                        </a>
                        <a class="btn-quickview" href="#qv<?php echo $_item->getId();?>"><i class="fa fa-search-plus"></i><span>Quick view</span></a>
                    </div>
                    <div class="content">
                        <h3 class="title">
                            <a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                            <?= $block->escapeHtml($_item->getName()) ?></a>
                        </h3>
                         <div class="info"><span class="price"><?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?></span></div>
                    </div>
                </div>
            </li>

            <div class="quickview-modal single-product remodal" data-remodal-id="qv<?php echo $_item->getId();?>">
                <button class="remodal-close" data-remodal-action="close" aria-label="Close"></button>
                <div class="single-product-detail customScrollbar" data-scroll-cursorcolor="#b9b9b9"
                     data-scroll-cursorwidth="3px">
                    <div class="row-cs">
                        <div class="col-cs-6 product-image-content">
                            <div class="image-box"><img src="<?php echo $block->getUrl('pub/media/catalog').'product'.$_item->getImage();?>" /></div>
                        </div>
                        <div class="col-cs-6 product-summary">
                            <h3 class="product-title text-block m-b-10">
                                <a class="text-black" href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */ echo $_item->getName() ?>
                                </a>
                            </h3>

                            <span class="product-price m-b-15"><?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?></span>
                            <p class="product-short-description m-b-15">
                                <?php echo $_item->getShortDescription(); ?>
                            </p>
                            <div class="add-to-wishlist block-contain m-b-40">
                                <div class="block-left" data-toggle="tooltip" title="Add to wishlist">
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a class="au-btn au-btn-border au-btn-radius btn-add-to-wishlist" href="#"
                                           data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                        <i class="fa fa-heart"></i><span><?php echo __('ADD TO WISHLIST'); ?></span>
                                        </a>
                                    <?php endif;?>
                                </div>
                                <div class="block-right" data-toggle="tooltip" title="View full details">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>">
                                        <i class="fa fa-arrow-right"></i><span><?php echo __('Go to detail'); ?></span>
                                    </a>
                                </div>
                            </div>
                            <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                            <form action="<?php echo /* @escapeNotVerified */  $postParams['action']?>" method="post"
                                  id="product_addtocart_form_<?php echo $_item->getId();?>" enctype="multipart/form-data">
                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $_item->getId() ?>" />
                                <input type="hidden" name="selected_configurable_option" value="" />
                                <input type="hidden" name="related_product" id="related-products-field-<?php echo $_item->getId();?>" value="" />
                                <?= $block->getBlockHtml('formkey') ?>
                                <div class="product-select row-cs m-b-20">
                                    <?php if (!$block->hasOptions()):?>
                                    <div class="col-cs-6 p-l-5" data-toggle="tooltip" title="Quantity">
                                        <div class="quantity">
                                            <span class="decrease"></span>
                                            <input class="au-input-number"
                                                   name="qty"
                                                   id="qty_<?php echo $_item->getId();?>"
                                                   value="<?= /* @escapeNotVerified */ __('1') ?>"
                                                   title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                                                   type="number" value="1" min="1" max="100"/>
                                            <span class="increase"></span></div>
                                    </div>
                                </div>
                                <button class="au-btn add-to-cart btn-block m-b-30" type="submit"><?php echo __('ADD TO CART') ?></button>
                            <?php endif; ?>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach ?>
        </ul>
        <?php endif;?>
    </div>
</section>
<?php endif;?>
