<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list template
 *
 * @var $block \Magefan\Blog\Block\Post\PostList
 */
?>
<?php
$_postCollection = $block->getPostCollection();
?>
<div class="page-content blog-list-page-1 p-t-40 p-b-100">
<?php if (!$_postCollection->count()): ?>
    <div class="message info empty"><div><?php echo __('We can\'t find posts matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getAdditionalHtml() ?>
    <div class="article-wrapper">
        <?php $iterator = 1; ?>
        <ul class="blog-list list-reset">
        <?php foreach ($_postCollection as $_post): ?>
            <li><?php echo $block->getPostHtml($_post) ?></li>
        <?php endforeach; ?>
        </ul>
    </div>

    <?php echo $block->getToolbarHtml() ?>
    <?php echo $this->getChildHtml('addthisJs'); ?>
<?php endif; ?>
</div>
