<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>


<?php if ($crumbs && is_array($crumbs)) : ?>
    <div class="heading-page bg-cover">
        <div class="container">
            <ul class="breadcrumbs">
                <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                    <li>
                    <?php if ($crumbInfo['link']) : ?>
                        <a href="<?php /* @escapeNotVerified */ echo $crumbInfo['link'] ?>" title="<?php echo $block->escapeHtml($crumbInfo['title']) ?>">
                            <?php echo strtoupper($block->escapeHtml($crumbInfo['label'])) ?>
                        </a>
                    <?php elseif ($crumbInfo['last']) : ?>
                        <a><?php echo strtoupper($block->escapeHtml($crumbInfo['label'])) ?></a>
                    <?php else: ?>
                        <?php echo strtoupper($block->escapeHtml($crumbInfo['label'])) ?>
                    <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>
