<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
?>
<?php if ($block->getLayout()->getBlock('page.main.title')->getPageTitle() == 'Home Page'):?>
	<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mina-nav1')->toHtml();?>
<?php else: ?>
	<?php  echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mina-nav2')->toHtml();?>
<?php endif;?>
