<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
    $_post = $this->getPost();
    $_postUrl = $_post->getPostUrl();
    $_postName = $block->escapeHtml($_post->getTitle(), null, true);

?>
<div class="image-box image-box-6 image-box-6--large">
    <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
        <div class="image">
            <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
            </a>
        </div>
    <?php } ?>
    <div class="content"><span class="date"><?php echo date_format(new DateTime($_post->getPublishDate()),"F d, Y"); ?></span>
        <h3 class="title">
            <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                <?php echo $_postName ?>
            </a></h3>
        <p class="textbox"><?php echo $_post->getShortContent() ?></p>
        <a class="text-hover-animate read-more" href="<?php echo $_postUrl ?>">Read more</a>
    </div>
</div>